### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by mizzunet** [hassansin/send-to-kindle#1]
I happened to see this project, https://github.com/hassansin/send-to-kindle and I do own a Kindle, I was super exxited till knowing that webtask.io has been depreciated :(
So, I wonder by any chance, could you make it working using any other fee suitable serverless platform from here, https://github.com/anaibol/awesome-serverless#what-is-serverless-computing. That would be greatly appericiable. 

Thanks in advace :)

**Comment by hassansin** [comment]
Sorry, I stopped using Kindle for some time. I've no plans to fix the script any time soon.
